# Generated by Django 6.0.2 on 2026-03-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="Статья опубликована"
            ),
        ),
    ]
