# Generated by Django 6.0.2 on 2026-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="creation_at",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(auto_now=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
