# Generated by Django 6.0.2 on 2026-04-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.CharField(
                choices=[
                    ("published", "опубликован"),
                    ("unpublished", "не опубликован"),
                ],
                default="не опубликован",
                verbose_name="Статус публикации",
            ),
        ),
    ]
